### ISSUE TITLE
Client-Side timeout exceeded for operation

### ISSUE THREAD

**Issue by StarpTech** [cha87de/couchbase-docker-cloudnative#1]
Hi, I get this error when I setup couchbase with your image. I'm using couchnode driver.
```
CouchbaseError: Client-Side timeout exceeded for operation. Inspect network conditions or increase the timeout
```
When I use the official image it works
```
docker run -d --name db -p 8091-8094:8091-8094 -p 11210:11210 couchbase
```

Thats my config:

```
version: "3"
services:
  couchbase:
    image: cha87de/couchbase-cloudnative
    environment:
      - CLUSTER=localhost
      - USER=admin
      - PASS=secret
      - PORT=8091
      - RAMSIZEMB=1024
      - RAMSIZEINDEXMB=256
      - RAMSIZEFTSMB=256
      - BUCKETS=default
      - BUCKETSIZES=256
      - AUTOREBALANCE=true
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
      - 11211:11211
```

Logs:

```
couchbase_1  | Starting Couchbase Server -- Web UI available at http://<ip>:8091 and logs available in /opt/couchbase/var/lib/couchbase/logs
couchbase_1  | now initializing couchbase ...
couchbase_1  | try initialization
couchbase_1  | failed to initialize cluster.
couchbase_1  | 1 retries. retry in 5s.
couchbase_1  | Unable to connect to host at http://localhost:8091
couchbase_1  | cannot initialize couchbase
couchbase_1  | try initialization
couchbase_1  | Unable to connect to host at http://localhost:8091
couchbase_1  | cannot initialize couchbase
couchbase_1  | failed to initialize cluster.
couchbase_1  | 2 retries. retry in 5s.
couchbase_1  | try initialization
couchbase_1  | SUCCESS: init/edit localhost
couchbase_1  | try to add host (if not already added) to cluster
couchbase_1  | Error: Failed to add server 172.19.0.2:8091: Prepare join failed. Joining node to itself is not allowed.
couchbase_1  | failed to add host to cluster
couchbase_1  | failed to add server to cluster.
couchbase_1  | 1 retries. retry in 5s.
couchbase_1  | server is already part of the cluster. skipping.
couchbase_1  | try to create buckets
couchbase_1  | create bucket default with size 256
couchbase_1  | ...SUCCESS: bucket-create
couchbase_1  | now wait for couchbase forever
```
